In [1]:
l1 = [10, 34, 56, 54, 78, 77, 24, 59, 8, 2, 5, 88, 20, 29, 100, 92, 81]

In [2]:
for ele in l1:
    if ele > 30 and ele < 80:
        print(ele)

34
56
54
78
77
59


In [4]:
res = list()
for ele in l1:
    if ele > 30 and ele < 80:
        res.append(ele)
res

[34, 56, 54, 78, 77, 59]

In [6]:
[ele for ele in l1]


[10, 34, 56, 54, 78, 77, 24, 59, 8, 2, 5, 88, 20, 29, 100, 92, 81]

In [7]:
[ele for ele in l1 if ele > 30 and ele < 80]

# List comprehensions

[34, 56, 54, 78, 77, 59]

In [9]:
t1 = 10, 34, 56, 54, 78, 77, 24, 59, 8, 2, 5, 88, 20, 29, 100, 92, 81

In [10]:
[ele for ele in t1 if ele > 30 and ele < 80]

[34, 56, 54, 78, 77, 59]

In [11]:
# Dict
# Creation
d1 = {'maths':90,'phy':86,'che':77,'eng':85,'cs':70}
d1

{'maths': 90, 'phy': 86, 'che': 77, 'eng': 85, 'cs': 70}

In [12]:
type(d1)

dict

In [13]:
{'maths':90,'phy':86,'che':77,'eng':85,'cs':70,'maths':95}

{'maths': 95, 'phy': 86, 'che': 77, 'eng': 85, 'cs': 70}

In [17]:
d2 = {'ele1':9283, 2.5:2301, 3:93944, 4:'abc', (1,2,3):319992, "score":[2,42,4,2,4,2],"subjects":d1}
d2

{'ele1': 9283,
 2.5: 2301,
 3: 93944,
 4: 'abc',
 (1, 2, 3): 319992,
 'score': [2, 42, 4, 2, 4, 2],
 'subjects': {'maths': 90, 'phy': 86, 'che': 77, 'eng': 85, 'cs': 70}}

In [20]:
# Accessing elements
# there are no indexes

# to extract 77, which is the 3rd element, pass index as 2
d1[2]
# it won't work as 2 is not the index of 77 like tuple and list
# in fact, there are no indexed at allllll

KeyError: 2

In [30]:
# we extract 77 by knowing it's key and passing it to the []
d1.keys()

dict_keys(['maths', 'phy', 'che', 'eng', 'cs'])

In [31]:
list(d1.keys())

['maths', 'phy', 'che', 'eng', 'cs']

In [22]:
d1.values()

dict_values([90, 86, 77, 85, 70])

In [26]:
d1['che']

77

In [27]:
d2.keys()

dict_keys(['ele1', 2.5, 3, 4, (1, 2, 3), 'score', 'subjects'])

In [25]:
d2.values()

dict_values([9283, 2301, 93944, 'abc', 319992, [2, 42, 4, 2, 4, 2], {'maths': 90, 'phy': 86, 'che': 77, 'eng': 85, 'cs': 70}])

In [29]:
d2[4]

# 4 here is not an index!!!!!
# it's an existing key of dict d2
# otherwise we'll get KeyError

'abc'

In [32]:
# Iterations on a dictionary

# an iteration on list/tuple, it happens on their value, not their indexes
for ele in l1:
    print(ele)

10
34
56
54
78
77
24
59
8
2
5
88
20
29
100
92
81


In [33]:
# but for a dict
# the interations is on the keys, not values
for i in d1:
    print(i)

maths
phy
che
eng
cs


In [36]:
# task : print all the scores from d1

for i in d1:
    print(d1[i])

90
86
77
85
70


In [37]:
for i in d1.values():
    print(i)

90
86
77
85
70


In [38]:
for i in d1:
    print(i," : ",d1[i])

maths  :  90
phy  :  86
che  :  77
eng  :  85
cs  :  70


In [41]:
print("subjects where the person has scored 90 and above")
for i in d1:
    if(d1[i] >= 90):
        print(i)

subjects where the person has scored 90 and above
maths


In [45]:
[12,54,"abc",True,l1,d1]

[12,
 54,
 'abc',
 True,
 [10, 34, 56, 54, 78, 77, 24, 59, 8, 2, 5, 88, 20, 29, 100, 92, 81],
 {'maths': 90, 'phy': 86, 'che': 77, 'eng': 85, 'cs': 70}]

In [47]:
EmpDict = {"EID":[11,22,33,44,55],
           "Ename":['abc', 'rty', 'ewq', 'yui', 'wwr'],
           "Sal":[4363,3436,2626,2462,6264]
          }
EmpDict

{'EID': [11, 22, 33, 44, 55],
 'Ename': ['abc', 'rty', 'ewq', 'yui', 'wwr'],
 'Sal': [4363, 3436, 2626, 2462, 6264]}

In [48]:
import pandas as pd
pd.DataFrame(EmpDict)

EID Ename   Sal
0   11   abc  4363
1   22   rty  3436
2   33   ewq  2626
3   44   yui  2462
4   55   wwr  6264

In [49]:
# Sets
s1 = {1,2,3,2,3,2,4,2,2,5,4,3,2,3}
type(s1)

set

In [50]:
s1

{1, 2, 3, 4, 5}

In [53]:
s2 = {'q',1,2,3,'q','q','t',2,'w',3,'d',2,'t',4,'t',2,2,5,4,3,2,3}
s2

{1, 2, 3, 4, 5, 'd', 'q', 't', 'w'}

In [54]:
# Functions

def func():
    pass

In [55]:
def AddTwoNums(x,y):
    res = x + y
    return res

In [57]:
Sum = AddTwoNums(10,20)

In [58]:
Sum

30

In [61]:
AddTwoNums(x=10,y=20)

30

In [62]:
AddTwoNums()

TypeError: AddTwoNums() missing 2 required positional arguments: 'x' and 'y'

In [63]:
def AddTwoNums_dflt(x=0,y=0):
    res = x + y
    return res

In [60]:
AddTwoNums(10)

TypeError: AddTwoNums() missing 1 required positional argument: 'y'

In [64]:
AddTwoNums_dflt()

0

In [65]:
AddTwoNums_dflt(10)

10

In [66]:
AddTwoNums(10,20,30,40)

TypeError: AddTwoNums() takes 2 positional arguments but 4 were given

In [67]:
AddTwoNums_dflt(10,20,40,20)

TypeError: AddTwoNums_dflt() takes from 0 to 2 positional arguments but 4 were given

In [69]:
# Function Overloading
x = 839
print("abc")
print("The value of x is :",x,"and the square is",x**2)

abc
The value of x is : 839 and the square is 703921


In [ ]:
# Task :  Create a function : Sum()
#         Sum() should take inf number of arguments
#         and all all of those and return the sum

In [71]:
t1

s = 0
for ele in t1:
    s = s + ele
s

817

In [89]:
def Sum(*args):
    s = 0
    for ele in args:
        if type(ele) == int or type(ele) == float:
            s = s + ele
    return s

In [90]:
Sum(12,43,23,54,23,'abc')

155

In [82]:
Sum(10,20)

30

In [83]:
Sum(20,40,50)

110

In [91]:
d1

{'maths': 90, 'phy': 86, 'che': 77, 'eng': 85, 'cs': 70}

In [95]:
s = 0
for i in d1.values():
    s += i
    
avg = s/len(d1)
avg

print("The avg score in",list(d1.keys()),"is",avg)

The avg score in ['maths', 'phy', 'che', 'eng', 'cs'] is 81.6


In [ ]:
# Task : Create a function named ScoreCalc()
#       it should take marks as input
#       but that should be with a custom key word

Sum(90,88,70)
ScoreCalc(math=90,phy=88,che=70)
ScoreCalc(eco=80,comm=70,math=90,eng=85)

In [99]:
def ScoreCalc(**kwargs):
    s = 0
    for i in kwargs.values():
        s += i
    
    avg = s/len(kwargs)
    print("The avg score in",list(kwargs.keys()),"is",avg)


In [97]:
def Demo(**x):
    print(x)

In [98]:
Demo(d=6,g=78,q=76,y=647,srh=643)

{'d': 6, 'g': 78, 'q': 76, 'y': 647, 'srh': 643}


In [100]:
ScoreCalc(math=90,phy=88,che=70)

The avg score in ['math', 'phy', 'che'] is 82.66666666666667


In [101]:
ScoreCalc(eco=80,comm=70,math=90,eng=85)

The avg score in ['eco', 'comm', 'math', 'eng'] is 81.25


In [102]:
l1

[10, 34, 56, 54, 78, 77, 24, 59, 8, 2, 5, 88, 20, 29, 100, 92, 81]

In [103]:
t1

(10, 34, 56, 54, 78, 77, 24, 59, 8, 2, 5, 88, 20, 29, 100, 92, 81)

In [104]:
s1

{1, 2, 3, 4, 5, 'd', 'q', 't', 'w'}

In [105]:
d1

{'maths': 90, 'phy': 86, 'che': 77, 'eng': 85, 'cs': 70}

In [108]:
tuple(l1)
set(l1)
dict(l1)

TypeError: cannot convert dictionary update sequence element #0 to a sequence

In [112]:
tuple(d1)
list(d1)


['maths', 'phy', 'che', 'eng', 'cs']

In [113]:
?print

In [114]:
# Mapping
# process by which we apply a function to any data-structure without 
# using loops
# map() function takes a function and the ds as inputs and applies the function
# on that data structure

def square(x):
    return x ** 2

In [115]:
square(9)

81

In [ ]:
res = []
for ele in l1:
    res.append(square(ele))
res

In [122]:
list(map(square,l1))

[100,
 1156,
 3136,
 2916,
 6084,
 5929,
 576,
 3481,
 64,
 4,
 25,
 7744,
 400,
 841,
 10000,
 8464,
 6561]

In [123]:
def isodd(x):
    if x%2 != 0:
        return True
    else:
        return False

In [124]:
res = list()
for ele in l1:
    res.append(isodd(ele))
res

[False,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True]

In [127]:
list(map(isodd,l1))
# map takes function and DS as inputs
# applies the function on that DS
# the function can be anything and it may return anything!

[False,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True]

In [126]:
list(filter(isodd,l1))
# filter takes function and DS as inputs
# applies the function on that DS
# the function should be returning boolean values
# it return the values correspnding to True

[77, 59, 5, 29, 81]

In [128]:
# Lambda functions
# anonymous functions
# meant for the single lined functions
# we don't have to actually define a single line function using def
# we can instead create them anonymously using lambda

# lambda arg:return

def square(x):
    return x**2

lambda x:x**2

<function __main__.<lambda>(x)>

In [131]:
print(list(map(square,l1)))

[100, 1156, 3136, 2916, 6084, 5929, 576, 3481, 64, 4, 25, 7744, 400, 841, 10000, 8464, 6561]


In [132]:
print(list(map(lambda x:x**2,l1)))

[100, 1156, 3136, 2916, 6084, 5929, 576, 3481, 64, 4, 25, 7744, 400, 841, 10000, 8464, 6561]


In [133]:
print(list(map(lambda x:x*10,l1)))

[100, 340, 560, 540, 780, 770, 240, 590, 80, 20, 50, 880, 200, 290, 1000, 920, 810]


In [134]:
# Python files, with the extention of .py are called modules
# they contain codes : 
#         - functions
#         - variables
# and these modules are REUSABLE!!


# .ipynb
# default py code extion is .py

In [ ]:
# How to make a certeain .py file available globlally?
# step 1 : 
#      create a py file
# step 2 : 
#      where is the installation directory
# step 3 :
#      Windows : 
#      locate the Lib folder and copy the module there
#      locate site-packages inside Lib and copy a package there

#      Mac/Linux : 
#      Copy it in the anaconda folder > Python 3.7.xxxx folder
#      
# Step 4 :
#      import and use all the functions
#      this is done using the import function



In [135]:
# import module name/package name
import misc_utils

In [136]:
print(dir(misc_utils))

['Calculator', 'ScoreCard', 'Sum', 'SumOfNums', 'Sum_def', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'batch', 'city', 'course', 'pi', 'power_calc']


In [137]:
misc_utils.course

'DSP'

In [138]:
misc_utils.power_calc(25,2)

625

In [139]:
# importing
# we use import
# we need specific things only to be imported not everything
#     -  a specific function from a module
#                 from module_name import f1,f2,f3

#     -  a specific module from a package
#                 from package import m1,m2,m3

# to access the elements from the imported module or packages
#         we need to always follow the notation module.element
#         importing doesn;t guarentee you the usage

In [141]:
misc_utils.pi

3.142

In [142]:
# use of aliases
import misc_utils as mu

In [143]:
misc_utils.Calculator(10,20)

[30, -10, 200, 0, 10]

In [144]:
mu.Calculator(10,20)

[30, -10, 200, 0, 10]

In [145]:
from matplotlib import pyplot as plt

In [148]:
#matplotlib.pyplot.hist()
#plt.hist()

In [149]:
# Pacakge
# a folder which is a collection of modlues and other compiled codes 
# for a folder to qualify as a package, it must have an initiator module
#         __init__.py
#        

In [150]:
# Classes
class example:
    pass


In [151]:
type(example)
# it's a datatype

type

In [152]:
# creating objects
# instantiation
# DONE using a contructor
o1 = example()

In [153]:
type(o1)

__main__.example

In [155]:
class example:
    x = 10
    y = 20
    
    def MyFunc(self,x):
        print(x)
        

In [156]:
o1 = example()

In [157]:
print(dir(o1))

['MyFunc', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'x', 'y']


In [158]:
o2 = example()
print(dir(o2))

['MyFunc', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'x', 'y']


In [159]:
o1.x

10

In [160]:
o2.x

10

In [161]:
o1.MyFunc(10)

10


In [162]:
o2.MyFunc(30)

30


In [163]:
# Create constructors!
# Class for Cars

# make =  model =  color =  engine =  abs =  price =  top_speed =  mileage

class Cars:
    make = "Hyundai"
    model = "Verna"
    color = "blue"
    engine =  "1600cc"
    has_abs =  "yes"
    transmission = "auto"
    price =  110000
    top_speed = 160
    mileage = 16
    
    def acc(self):
        pass
    def deacc(self):
        pass
    def turn(self, how = "right"):
        pass



In [164]:
c1 = Cars()

In [166]:
c1.model

'Verna'

In [167]:
c2 =Cars()

In [169]:
c2.model = "Swift"

In [170]:
c2.make = "Maruti"

In [171]:
c2.make

'Maruti'

In [175]:
class Cars:
    
    def __init__(self,make="",model="",color="",engine="",has_abs=False,transmission="manual",price=0,top_speed=0,mileage=0):
        self.make = make
        self.model = model
        self.color = color
        self.engine =  engine
        self.has_abs =  has_abs
        self.gears = transmission
        self.price =  price
        self.top_speed = top_speed
        self.mileage = mileage

    
    def acc(self):
        pass
    def deacc(self):
        pass
    def turn(self,how = "right"):
        pass



In [177]:
o1 = Cars()

In [178]:
o1.color

''

In [179]:
o1.gears

'manual'

In [180]:
o1.has_abs

False

In [181]:
o2 = Cars(model="CyberTruck",make="Tesla",color="grey",mileage="650km",top_speed="200")

In [182]:
o2.color

'grey'

In [183]:
import numpy as np

In [186]:
# 1. Creating arrays
# we can convert a list, tuple, set or dict.values() to array

arr1 = np.array(l1)

In [187]:
type(arr1)

numpy.ndarray

In [188]:
arr1

array([ 10,  34,  56,  54,  78,  77,  24,  59,   8,   2,   5,  88,  20,
        29, 100,  92,  81])

In [190]:
# 2. Accessing elements
# the [] extractor
arr1[5]

77

In [191]:
arr1[3:9]

array([54, 78, 77, 24, 59,  8])

In [197]:
# task : in list l1, get all elements from pos 2,8,8,12,13
# for i in range(0,len(l1)):
#     if i in [2,8,8,12,13]:
#         print(l1[i])
        
        
for i in [2,8,9,12,13]:
    print(l1[i])

56
8
2
20
29


In [198]:
# task : in array arr1, get all elements from pos 2,8,9,12,13
for i in [2,8,9,12,13]:
    print(arr1[i])

56
8
2
20
29


In [200]:
arr1[[2,8,9,12,13]]

array([56,  8,  2, 20, 29])

In [201]:
arr1[[4,6,7,8,9]]

array([78, 24, 59,  8,  2])

In [203]:
# 3. Applying conditions on array

# from list l1, get all elements > 30 and < 80
res = []
for i in l1:
    if i > 30 and i < 80:
        res.append(i)
res

[34, 56, 54, 78, 77, 59]

In [204]:
# vectorized DS contain something called - Boolean indexes
arr1 > 30

array([False,  True,  True,  True,  True,  True, False,  True, False,
       False, False,  True, False, False,  True,  True,  True])

In [205]:
arr1[(arr1 > 30)]

array([ 34,  56,  54,  78,  77,  59,  88, 100,  92,  81])

In [207]:
arr1[(arr1 > 30) & (arr1 < 80)]

array([34, 56, 54, 78, 77, 59])

In [209]:
# 4. Attributes
print(dir(arr1))

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rlshift_

In [ ]:
# 5. Properties
# 5.1 Vectorization
#      -  accessing multiple elements
#      -  applying conditions - boolean indexes

In [211]:
# 5.2 Broadcasting

l2 = [10,30,70,5]
l3 = [30,20,4,10]

# Task : add the corresponding elements of l2 and l3

l2 + l3

for i in l2:
    print(i)

10
30
70
5


In [217]:
arr2 = np.array([10,30,70,5])
arr3 = np.array([30,20,4,10])

# if two arrays are of same length and datatype(numbers) 
# we can apply any arithmatic on them
# those two arrays

arr2 + arr3
arr2 / arr3

array([ 0.33333333,  1.5       , 17.5       ,  0.5       ])

In [222]:
# 5.3

arr1 + 100


array([110, 134, 156, 154, 178, 177, 124, 159, 108, 102, 105, 188, 120,
       129, 200, 192, 181])

In [224]:
arr1[9:13] = 1000

In [225]:
arr1

array([  10,   34,   56,   54,   78,   77,   24,   59,    8, 1000, 1000,
       1000, 1000,   29,  100,   92,   81])

In [229]:
np.array(list(map(lambda x:x**2,arr1)))

array([    100,    1156,    3136,    2916,    6084,    5929,     576,
          3481,      64, 1000000, 1000000, 1000000, 1000000,     841,
         10000,    8464,    6561])

In [231]:
arr1

array([  10,   34,   56,   54,   78,   77,   24,   59,    8, 1000, 1000,
       1000, 1000,   29,  100,   92,   81])

In [232]:
arr4 = np.array([9,2,4,8.9,2.3,4.5])
arr4

array([9. , 2. , 4. , 8.9, 2.3, 4.5])

In [233]:
arr5 = np.array([9,'a',2,4,8.9,2.3,4.5,"abd","pqr"])
arr5

array(['9', 'a', '2', '4', '8.9', '2.3', '4.5', 'abd', 'pqr'],
      dtype='<U11')

In [230]:
# Pandas
import pandas as pd

In [235]:
# Series
# 1 dimentional, homogenous data structure
# 1. Creating

ser1 = pd.Series(l1)
type(ser1)

pandas.core.series.Series

In [239]:
ser1

0      10
1      34
2      56
3      54
4      78
5      77
6      24
7      59
8       8
9       2
10      5
11     88
12     20
13     29
14    100
15     92
16     81
dtype: int64

In [242]:
print(list('abcdefghijklmnopq'))

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q']


In [243]:
ser2 = pd.Series(l1, index=['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q'])
# indexs needs to be the same size as that of the numeber of elements
ser2

# iloc of ser2 : 0 to n-1
# loc : a - q

a     10
b     34
c     56
d     54
e     78
f     77
g     24
h     59
i      8
j      2
k      5
l     88
m     20
n     29
o    100
p     92
q     81
dtype: int64

In [244]:
ser3 = pd.Series(l1)

In [246]:
ser3.index = range(1,18)

In [247]:
ser3

1      10
2      34
3      56
4      54
5      78
6      77
7      24
8      59
9       8
10      2
11      5
12     88
13     20
14     29
15    100
16     92
17     81
dtype: int64

In [250]:
ser1

ser1.iloc[4]
# loc == iloc

78

In [251]:
ser1.loc[4]

78

In [253]:
ser3.iloc[4]

78

In [255]:
ser3.loc[4]

54

In [257]:
ser2.iloc[5]

77

In [259]:
ser2.loc["f"]

77

In [263]:
ser1.iloc[5:15]

5      77
6      24
7      59
8       8
9       2
10      5
11     88
12     20
13     29
14    100
dtype: int64

In [264]:
ser1.loc[5:15]

5      77
6      24
7      59
8       8
9       2
10      5
11     88
12     20
13     29
14    100
15     92
dtype: int64

In [267]:
# Applying conditions
# .iloc[] : inter indexing only

# we need boolean index
# the boolean index MUST be passed to .loc[]

ser1 > 30

0     False
1      True
2      True
3      True
4      True
5      True
6     False
7      True
8     False
9     False
10    False
11     True
12    False
13    False
14     True
15     True
16     True
dtype: bool

In [268]:
# get all eleemtns in ser1 that are > 30

ser1.loc[(ser1 > 30)]

1      34
2      56
3      54
4      78
5      77
7      59
11     88
14    100
15     92
16     81
dtype: int64

In [269]:
ser1.loc[(ser1 > 30) & (ser1 < 80)]

1    34
2    56
3    54
4    78
5    77
7    59
dtype: int64

In [270]:
# Attributes
print(dir(l1))

['__add__', '__class__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']


In [271]:
print(dir(arr1))

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rlshift_

In [272]:
print(dir(ser1))

['T', '_AXIS_ALIASES', '_AXIS_IALIASES', '_AXIS_LEN', '_AXIS_NAMES', '_AXIS_NUMBERS', '_AXIS_ORDERS', '_AXIS_REVERSED', '_HANDLED_TYPES', '__abs__', '__add__', '__and__', '__array__', '__array_priority__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__div__', '__divmod__', '__doc__', '__eq__', '__finalize__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__imod__', '__imul__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__long__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdiv__', '__rdivmod__', '__reduce__